# Intro to Tensors

In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2023-02-10 20:39:18.347740: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


2.11.0


creating tensors

In [2]:
scalar = tf.constant(7)

2023-02-10 20:39:25.184916: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
scalar.ndim
vector = tf.constant([10, 10])
vector.ndim
matrix = tf.constant([[10, 7], [7, 10]])
matrix.ndim
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [4]:
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]],
                      [[13, 14, 15], [16, 17, 18]]])
tensor.ndim


3

In [12]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

random tensors

In [6]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3, 2))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3, 2))


shuffle a tensor

valuable for when you want to shuffle your data so the inherent order doesnt effect your learning

In [7]:
tf.random.set_seed(42)
tf.random.shuffle(random1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702]], dtype=float32)>

create tensor with np arrays

the main diff between np arrays and tensors is that tensors can be run on a gpu for computing faster

In [8]:
tf.ones([10, 7])
tf.zeros([3, 4])


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [9]:
numpy_A = np.arange(1, 25)
B = tf.constant(numpy_A)
A = tf.constant(numpy_A, shape=(2, 3, 4))
A, B


(<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int64, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

Getting info from tensors

In [10]:
rank4_tensor = tf.zeros([2, 3, 4, 5], tf.int8)
rank4_tensor.shape, rank4_tensor.ndim, tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

indexing tensors

In [19]:
rank4_tensor[:1,:1]

<tf.Tensor: shape=(1, 1, 4, 5), dtype=int8, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int8)>

In [21]:
E = tf.constant(np.random.randint(0,100,size=50))

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [23]:
tf.reduce_min(E)
tf.reduce_max(E)
tf.reduce_mean(E)
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2257>

In [34]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32)).numpy()
tf.math.reduce_std(tf.cast(E,dtype=tf.float32)).numpy()

28.641235

finding the positional min,max,etc

In [42]:
tf.random.set_seed(0)
F = tf.random.uniform(shape=[50])

In [49]:
tf.argmax(F) # finds the index of max

# both of the below do the same thing
F[tf.argmax(F)]
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99812925>